hiredup/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from work.views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('work.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from work.views import home_view, VacancySearchView
from . import views

urlpatterns = [
    path('',home_view,name='home'),
    path('vacancy/<int:vacancy_id>/', views.vacancy_detail_view, name = 'vacancy_detail'),
    path('vacancy/<int:vacancy_id>/apply/', views.apply_to_vacancy, name='apply_to_vacancy'),
    path('applications/', views.applications_view, name='applications'),
    path('application/<int:application_id>/', views.application_detail_view, name='application_detail'),
    path('application/<int:application_id>/update_status/', views.update_application_status, name='update_application_status'),
    path('search/', VacancySearchView.as_view(), name='search'),
    path('vacancies/', views.employer_vacancies_view, name='employer_vacancies'),  # Страница со списком вакансий
    path('vacancy/edit/<int:vacancy_id>/', views.edit_vacancy_view, name='edit_vacancy'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.contrib.auth.models import User  # Базовая модель пользователя Django
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from django.utils import timezone
from work.models import Profession


# Класс для хранения типов пользователей
class UserType(models.Model):
    USER_TYPES = [
        ('admin', 'Admin'),
        ('employer', 'Employer'),
        ('job_seeker', 'Job Seeker'),
        ('moderator', 'Moderator'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_type')
    user_type = models.CharField(verbose_name='Тип пользователя', max_length=20, choices=USER_TYPES)

    def __str__(self):
        return f"{self.user.username} - {self.get_user_type_display()}"

# Класс для профиля работодателей
class EmployerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employer_profile')
    company_name = models.CharField(verbose_name='Имя компании', max_length=255, blank=True, null=True)
    company_description = models.TextField(verbose_name='Описание компании', blank=True, null=True)
    company_address = models.CharField(verbose_name='Адрес компании', max_length=255, blank=True, null=True)
    company_logo = models.ImageField(upload_to='users/static/users/img', default='users/static/users/img/defaultCompanyAvatar.svg')
    created_at = models.DateTimeField('Дата создания', default=timezone.now)

    def __str__(self):
        return self.company_name if self.company_name else f"Employer {self.user.username}"

# Класс для резюме
class Resume(models.Model):
    job_seeker_profile = models.ForeignKey('JobSeekerProfile', on_delete=models.CASCADE, related_name='resumes', default=None)
    EDUCATION_CHOICES = [
        ('none', 'Без образования'),
        ('school', 'Школьное образование'),
        ('bachelor', 'Бакалавр'),
        ('master', 'Магистр'),
        ('phd', 'Аспирант'),
        ('doctorate', 'Доктор наук'),
    ]
    education = models.CharField(max_length=20, choices=EDUCATION_CHOICES)
    summary = models.TextField(blank=True, null=True, verbose_name='Общий текст резюме')
    skills = models.TextField(blank=True, null=True, verbose_name='Навыки')
    experience = models.PositiveIntegerField(
        verbose_name="Опыт работы (в годах)",
        validators=[
            MinValueValidator(0, message="Опыт работы не может быть меньше 0 лет"),
            MaxValueValidator(50, message="Опыт работы не может быть больше 50 лет")
        ],
        help_text="Введите количество лет опыта (от 0 до 50)",
        blank=True,
        null=True
    )
    languages = models.TextField(blank=True, null=True, verbose_name='Знание языков')
    file = models.FileField(upload_to='users/static/users/resumes', null=True, blank=True)
    created_at = models.DateTimeField('Дата создания', default=timezone.now)

    def __str__(self):
        return f"Resume {self.id} - {self.job_seeker_profile.user.username}"

# Класс для профиля соискателей работы
class JobSeekerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='job_seeker_profile')
    resume = models.OneToOneField(Resume, on_delete=models.SET_NULL, null=True, blank=True)
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE, related_name='job_seekers', null=True, blank=True)
    created_at = models.DateTimeField('Дата создания', default=timezone.now)
    status = models.BooleanField(default=False)
    phone_number = models.CharField(
        max_length=15,
        blank=True,
        null=True,
        verbose_name='Номер телефона',
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', message="Введите корректный номер телефона")]
    )  # Новое поле для телефона
    date_of_birth = models.DateField(
        blank=True,
        null=True,
        verbose_name='Дата рождения'
    )  # Новое поле для даты рождения
    avatar = models.ImageField(
        upload_to='users/static/users/img',  # Папка для сохранения изображений
        default='users/static/users/img/defaultUserAvatar.svg',  # Значение по умолчанию
        blank=True,
        null=True,
        verbose_name='Аватар'
    )  # Новое поле для аватара

    def __str__(self):
        return f"Job Seeker {self.user.username}"

work/models.py
from django.db import models
from django.utils import timezone

# Класс категорий профессий
class JobCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название категории профессий')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')

    def __str__(self):
        return self.name

# Класс профессий
class Profession(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название профессии')
    category = models.ForeignKey(JobCategory, on_delete=models.CASCADE, related_name='professions', verbose_name='Категория')

    def __str__(self):
        return self.name

# Класс вакансий
class Vacancy(models.Model):  # Исправил опечатку с 'Vacansy'
    JOB_TYPES = [
        ('full_time', 'Полный рабочий день'),
        ('part_time', 'Неполный рабочий день'),
        ('contract', 'Контракт'),
        ('internship', 'Стажировка'),
    ]

    employer = models.ForeignKey('users.EmployerProfile', on_delete=models.CASCADE, verbose_name='Работодатель')
    title = models.CharField(max_length=255, verbose_name='Название вакансии')
    requirements = models.TextField(blank=True, null=True, verbose_name='Описание вакансии')
    responsibilities = models.TextField(blank=True, null=True, verbose_name='Обязанности')  # Исправил 'responsobilities'
    salary_min = models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')
    salary_max = models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')
    experience_required = models.IntegerField(blank=True, null=True, verbose_name='Требуемый опыт работы (в годах)')
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE, related_name='vacancies', verbose_name='Профессия')  # Связь с Profession
    category = models.ForeignKey(JobCategory, on_delete=models.RESTRICT, verbose_name='Категория профессии')
    location = models.CharField(max_length=255, blank=True, null=True, verbose_name='Место работы')
    is_active = models.BooleanField(default=True, verbose_name='Статус вакансии')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    job_type = models.CharField(max_length=20, choices=JOB_TYPES, verbose_name='Тип занятости')

    def __str__(self):
        return self.title

class Application(models.Model):
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('reviewed', 'Рассмотрено'),
        ('accepted', 'Принято'),
        ('rejected', 'Отклонено'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    def get_status_css_class(self):
        return {
            'pending': 'status pending',
            'reviewed': 'status reviewed',
            'accepted': 'status accepted',
            'rejected': 'status rejected',
        }.get(self.status, 'status')

    vacancy = models.ForeignKey(
        'work.Vacancy',
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Вакансия'
    )
    job_seeker = models.ForeignKey(
        'users.JobSeekerProfile',
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Соискатель'
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name='Дата подачи'
    )

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending', verbose_name='Статус отклика')

    def __str__(self):
        return f"Application: {self.job_seeker.user.username} to {self.vacancy.title}"

work/forms.py
from django import forms
from .models import Vacancy

class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = [
            'title', 'requirements', 'responsibilities',
            'salary_min', 'salary_max', 'experience_required',
            'category', 'profession', 'location', 'job_type', 'is_active'
        ]

    # Кастомное поле для is_active с радиокнопками
    is_active = forms.BooleanField(
        required=False,
        widget=forms.RadioSelect(choices=[(True, 'Активная'), (False, 'Не активная')])
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.pk:  # Это создание новой вакансии
            self.fields['is_active'].initial = True  # Значение по умолчанию для новой вакансии
            self.fields['is_active'].widget = forms.HiddenInput()  # Скрыть поле для создания
        else:  # Это редактирование вакансии
            self.fields['is_active'].initial = self.instance.is_active  # Установить текущее значение для редактирования

work/templates/work/application_detail.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'work/css/application_detail.css' %}">
    <title>Детали отклика</title>
</head>
<body>
    <header class="top-panel">
        <div class="logotype">
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav>

        <a href="{% url 'home' %}">Главная</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Профиль</a>
            <form action="{% url 'logout' %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button class="leave" type="submit">Выйти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        {% endif %}
    </nav>
    </header>


        <h1>Детали отклика</h1>




    <section class="application-detail">
        <!-- Блок с информацией о вакансии -->
        <div class="vacancy-info">
            <h2>Вакансия: {{ vacancy.title }}</h2>
            <p><strong>Компания:</strong> {{ vacancy.employer.company_name }}</p>
            <p><strong>Описание вакансии:</strong> {{ vacancy.description }}</p>
            <p><strong>Зарплата:</strong> {{ vacancy.salary_min }} - {{ vacancy.salary_max }} руб.</p>
            <p><strong>Требования:</strong> {{ vacancy.requirements }}</p>
            <p><strong>Обязанности:</strong> {{ vacancy.responsibilities }}</p>
            <p><strong>Местоположение:</strong> {{ vacancy.location }}</p>
            <p><strong>Тип работы:</strong> {{ vacancy.get_job_type_display }}</p>
            <p><strong>Опыт работы:</strong> {{ vacancy_experience_display }} </p>
        </div>

        <!-- Блок с информацией о соискателе -->
        <div class="job-seeker-info">
            <h3>Информация о соискателе</h3>
            <p><strong>Никнейм:</strong> {{ job_seeker.user.username }}</p>
            <p><strong>Имя:</strong> {{ job_seeker.user.first_name }}</p>
            <p><strong>Фамилия:</strong> {{ job_seeker.user.last_name }}</p>
            <p><strong>Почта:</strong> {{ job_seeker.user.email }}</p>

            <h2>Резюме</h2>
            {% if job_seeker.resume %}
                <p><strong>О соискателе:</strong> {{ job_seeker.resume.summary }}</p>
                <p><strong>Образование:</strong> {{ job_seeker.resume.get_education_display }}</p>
                <p><strong>Навыки:</strong> {{ job_seeker.resume.skills }}</p>
                <p><strong>Знание языков:</strong> {{ job_seeker.resume.languages }}</p>
                <p>
                <strong>Опыт работы:</strong>
                {{ job_seeker_experience_display }}
                </p>
                <p><strong>Дата создания резюме:</strong> {{ job_seeker.resume.created_at|date:"d-m-Y" }}</p>
            {% else %}
                <p>Резюме отсутствует.</p>
            {% endif %}
        </div>


          <!-- Отображение сообщений -->
    <section class="messages">
        {% if messages %}
            <ul class="message-list">
                {% for message in messages %}
                    <li class="message {{ message.tags }}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>
    </section>
<!-- Блок с кнопками для принятия или отклонения отклика -->
        <div class="application-actions">
            <h3>Подтвердить отклик:</h3>
            {% if application.status != 'accepted' and application.status != 'rejected' %}
                <form method="POST" action="{% url 'update_application_status' application.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="accepted">
                    <button type="submit">Принять отклик</button>
                </form>
                <form method="POST" action="{% url 'update_application_status' application.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="rejected">
                    <button type="submit">Отклонить отклик</button>
                </form>
            {% else %}
                <p>Статус отклика уже изменен. Он не может быть изменен повторно.</p>
            {% endif %}
        </div>

</body>
</html>

work/templates/work/applications_employer.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'work/css/applications.css' %}">
    <title>Отклики на вакансии</title>
</head>
<body>
    <header class="top-panel">
        <div class="logotype">
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

       <nav>

        <a href="{% url 'home' %}">Главная</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Профиль</a>
            <form action="{% url 'logout' %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Выйти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        {% endif %}
    </nav>
    </header>


    <section class="applications-section">
        <h2>Отклики на ваши вакансии</h2>
        {% if page_obj %}
            <ul class="applications-list">
                {% for application in page_obj %}
                    <li class="application-item">
                        <div class="application-card">
                            <a href="{% url 'application_detail' application.id %}">{{ application.job_seeker.user.get_full_name }} (подробнее...)</a>
                            <p>Отклик на вакансию: <strong>{{ application.vacancy.title }}</strong></p>
                            <p>Статус: <span class="{{ application.get_status_css_class }}">{{ application.get_status_display }}</span></p>
                        <!-- Показываем кнопку только если отклик принят -->
                        {% if application.status == 'accepted' %}
                            <button class="contactBtn" data-modal-id="modal-{{ application.id }}">Написать соискателю</button>
                        {% endif %}
                        </div>
                    </li>

                    <!-- Модальное окно для отправки сообщения соискателю -->
                    <div id="modal-{{ application.id }}" class="modal">
                        <div class="modal-content">
                            <span class="close" data-modal-id="modal-{{ application.id }}">&times;</span>
                            <h3>Связаться с соискателем</h3>
                            <p>Вы можете написать на почту соискателя:</p>
                            {% if application.job_seeker.user.email %}
                                <a href="mailto:{{ application.job_seeker.user.email }}" target="_blank">{{ application.job_seeker.user.email }}</a>
                            {% else %}
                                <p>Почта не доступна.</p>
                            {% endif %}
                            <p>Номер телефона соискателя:
                                {% if application.job_seeker.phone_number %}
                                    {{ application.job_seeker.phone_number }}
                                {% else %}
                                    Номер не доступен.
                                {% endif %}
                            </p>
                        </div>
                    </div>

                {% endfor %}
            </ul>
        {% else %}
            <p>На ваши вакансии пока нет откликов.</p>
        {% endif %}
    </section>

    <!-- Навигация по страницам -->
    <section class="pagination-section">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">Первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
                {% endif %}

                <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Вперед</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                {% endif %}
            </span>
        </div>
    </section>

    <script>
        // Открытие и закрытие модальных окон
        document.querySelectorAll('.contactBtn').forEach(button => {
            button.addEventListener('click', function() {
                const modalId = this.getAttribute('data-modal-id');
                document.getElementById(modalId).style.display = "block";
            });
        });

        document.querySelectorAll('.close').forEach(span => {
            span.addEventListener('click', function() {
                const modalId = this.getAttribute('data-modal-id');
                document.getElementById(modalId).style.display = "none";
            });
        });

        // Закрытие модальных окон при клике за пределами окна
        window.addEventListener('click', function(event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = "none";
            }
        });
    </script>
</body>
</html>

work/templates/work/applications_job_seeker.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'work/css/applications.css' %}">
    <title>Мои отклики</title>
</head>
<body>
<header class="top-panel">
        <div class="logotype" >
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav>
        <a href="{% url 'home' %}">Главная</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Профиль</a>
            <form action="{% url 'logout' %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Выйти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        {% endif %}
    </nav>

    </header>

    <section class="applications-section">
        <h2>Отклики на вакансии</h2>
        {% if applications %}
            <ul class="applications-list">
                {% for application in applications %}
                    <li class="application-item">
                        <h3><a href="{% url 'vacancy_detail' application.vacancy.id %}">{{ application.vacancy.title }}    (подробнее...)</a></h3>

                        <p><strong>Вакансия:</strong> {{ application.vacancy.profession.name }}</p>
                        <p><strong>Компания:</strong> {{ application.vacancy.employer.company_name }}</p>
                        <p>Статус: <span class="{{ application.get_status_css_class }}">{{ application.get_status_display }}</span></p>
                        <!-- Показываем кнопку только если отклик принят -->
                        {% if application.status == 'accepted' %}
                            <button class="contactBtn" data-modal-id="modal-{{ application.id }}">Написать работодателю</button>
                        {% endif %}
                    </li>

                    <!-- Модальное окно для отправки сообщения работодателю -->
                    <div id="modal-{{ application.id }}" class="modal">
                        <div class="modal-content">
                            <span class="close" data-modal-id="modal-{{ application.id }}">&times;</span>
                            <h3>Связаться с работодателем</h3>
                            <p>Вы можете написать на почту работодателя:</p>
                            <!-- Проверка, что почта существует -->
                            {% if application.vacancy.employer.user.email %}
                                <a href="mailto:{{ application.vacancy.employer.user.email }}" target="_blank">{{ application.vacancy.employer.user.email }}</a>
                            {% else %}
                                <p>Почта не доступна.</p>
                            {% endif %}
                        </div>
                    </div>

                {% endfor %}
            </ul>
        {% else %}
            <p>У вас нет откликов на вакансии.</p>
        {% endif %}
    </section>

    <script>
        // Открытие и закрытие модальных окон
        document.querySelectorAll('.contactBtn').forEach(button => {
            button.addEventListener('click', function() {
                const modalId = this.getAttribute('data-modal-id');
                document.getElementById(modalId).style.display = "block";
            });
        });

        document.querySelectorAll('.close').forEach(span => {
            span.addEventListener('click', function() {
                const modalId = this.getAttribute('data-modal-id');
                document.getElementById(modalId).style.display = "none";
            });
        });

        // Закрытие модальных окон при клике за пределами окна
        window.addEventListener('click', function(event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = "none";
            }
        });
    </script>
</body>
</html>

work/templates/work/edit_vacancy.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'work/css/edit_vacancy.css' %}">
    <title>Редактирование вакансии</title>
</head>
<body>
    <header class="left-panel">
        <div class="logotype">
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav class="nav-menu">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Профиль</a>
            <a href="{% url 'applications' %}">Отклики</a>
            {% if user.employer_profile %}  <!-- Проверяем, является ли пользователь работодателем -->
            <a href="{% url 'employer_vacancies' %}">Мои вакансии</a>  <!-- Ссылка на страницу списка вакансий -->
        {% endif %}


        {% else %}

            <a href="{% url 'login' %}" >Войти</a>
            <button onclick="{% url 'register' %}" class="button">Зарегистрироваться </button>
        {% endif %}

    </nav>
    </header>

    <h1>Создание вакансии</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_title">Название вакансии
                <span class="tooltip">?<span class="tooltip-text">Укажите название вакансии.</span></span>
            </label>
            {{ form.title }}
        </div>

        <div class="form-group">
            <label for="id_requirements">Описание вакансии
                <span class="tooltip">?<span class="tooltip-text">Опишите требования и задачи.</span></span>
            </label>
            {{ form.requirements }}
        </div>

        <div class="form-group">
            <label for="id_responsibilities">Обязанности
                <span class="tooltip">?<span class="tooltip-text">Перечислите основные обязанности.</span></span>
            </label>
            {{ form.responsibilities }}
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="id_salary_min">Мин. зарплата
                    <span class="tooltip">?<span class="tooltip-text">Минимальная зарплата.</span></span>
                </label>
                {{ form.salary_min }}
            </div>
            <div class="form-group">
                <label for="id_salary_max">Макс. зарплата
                    <span class="tooltip">?<span class="tooltip-text">Максимальная зарплата.</span></span>
                </label>
                {{ form.salary_max }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_category">Категория профессии
                <span class="tooltip">?<span class="tooltip-text">Выберите категорию.</span></span>
            </label>
            {{ form.category }}
        </div>

        <div class="form-group">
            <label for="id_profession">Профессия
                <span class="tooltip">?<span class="tooltip-text">Выберите профессию.</span></span>
            </label>
            {{ form.profession }}
        </div>

        <div class="form-group">
            <label for="id_experience_required">Требуемый опыт (лет)
                <span class="tooltip">?<span class="tooltip-text">Требуемый опыт работы.</span></span>
            </label>
            {{ form.experience_required }}
            {% if form.experience_required.errors %}
            <ul class="error-list">
                {% for error in form.experience_required.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_job_type">Тип занятости
                <span class="tooltip">?<span class="tooltip-text">Выберите тип занятости.</span></span>
            </label>
            {{ form.job_type }}
        </div>

        <div class="form-group">
            <label for="id_location">Место работы
                <span class="tooltip">?<span class="tooltip-text">Укажите место работы.</span></span>
            </label>
            {{ form.location }}
        </div>

        <!-- Статус вакансии с радиокнопками для редактирования -->
        {% if form.is_active.widget != 'HiddenInput' %}
        <label for="id_is_active">Статус вакансии
            <span class="tooltip">?<span class="tooltip-text">Данная настройка отвечает за видимость вакансии на странице.</span></span>
        </label>
        <div class="status-options">
            <label>
                <input type="radio" name="is_active" value="True" {% if form.is_active.value == True %}checked{% endif %}> Активная
            </label>
            <label>
                <input type="radio" name="is_active" value="False" {% if form.is_active.value == False %}checked{% endif %}> Не активная
            </label>
        </div>
        {% endif %}

        <button type="submit">Сохранить изменения</button>
    </form>
</body>
</html>