hiredup/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from work.views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('work.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from work import views as W
urlpatterns=[
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate_account'),
    path('activation/',views.activation_view,name='activation'),
    path('activation/complete', views.activation_complete_view, name='activated'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('resume/', views.resume_view, name='resume_view'),
    path('load_professions/', views.load_professions, name='load_professions'),
    path('create-vacancy/', views.create_vacancy_view, name='create_vacancy'),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

work/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from work.views import home_view, VacancySearchView
from . import views

urlpatterns = [
    path('',home_view,name='home'),
    path('vacancy/<int:vacancy_id>/', views.vacancy_detail_view, name = 'vacancy_detail'),
    path('vacancy/<int:vacancy_id>/apply/', views.apply_to_vacancy, name='apply_to_vacancy'),
    path('applications/', views.applications_view, name='applications'),
    path('application/<int:application_id>/', views.application_detail_view, name='application_detail'),
    path('application/<int:application_id>/update_status/', views.update_application_status, name='update_application_status'),
    path('search/', VacancySearchView.as_view(), name='search'),
    path('vacancies/', views.employer_vacancies_view, name='employer_vacancies'),  # Страница со списком вакансий
    path('vacancy/edit/<int:vacancy_id>/', views.edit_vacancy_view, name='edit_vacancy'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.contrib.auth.models import User  # Базовая модель пользователя Django
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from django.utils import timezone
from work.models import Profession


# Класс для хранения типов пользователей
class UserType(models.Model):
    USER_TYPES = [
        ('admin', 'Admin'),
        ('employer', 'Employer'),
        ('job_seeker', 'Job Seeker'),
        ('moderator', 'Moderator'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_type')
    user_type = models.CharField(verbose_name='Тип пользователя', max_length=20, choices=USER_TYPES)

    def __str__(self):
        return f"{self.user.username} - {self.get_user_type_display()}"

# Класс для профиля работодателей
class EmployerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employer_profile')
    company_name = models.CharField(verbose_name='Имя компании', max_length=255, blank=True, null=True)
    company_description = models.TextField(verbose_name='Описание компании', blank=True, null=True)
    company_address = models.CharField(verbose_name='Адрес компании', max_length=255, blank=True, null=True)
    company_logo = models.ImageField(upload_to='users/static/users/img', default='users/static/users/img/defaultCompanyAvatar.svg')
    created_at = models.DateTimeField('Дата создания', default=timezone.now)

    def __str__(self):
        return self.company_name if self.company_name else f"Employer {self.user.username}"

# Класс для резюме
class Resume(models.Model):
    job_seeker_profile = models.ForeignKey('JobSeekerProfile', on_delete=models.CASCADE, related_name='resumes', default=None)
    EDUCATION_CHOICES = [
        ('none', 'Без образования'),
        ('school', 'Школьное образование'),
        ('bachelor', 'Бакалавр'),
        ('master', 'Магистр'),
        ('phd', 'Аспирант'),
        ('doctorate', 'Доктор наук'),
    ]
    education = models.CharField(max_length=20, choices=EDUCATION_CHOICES)
    summary = models.TextField(blank=True, null=True, verbose_name='Общий текст резюме')
    skills = models.TextField(blank=True, null=True, verbose_name='Навыки')
    experience = models.PositiveIntegerField(
        verbose_name="Опыт работы (в годах)",
        validators=[
            MinValueValidator(0, message="Опыт работы не может быть меньше 0 лет"),
            MaxValueValidator(50, message="Опыт работы не может быть больше 50 лет")
        ],
        help_text="Введите количество лет опыта (от 0 до 50)",
        blank=True,
        null=True
    )
    languages = models.TextField(blank=True, null=True, verbose_name='Знание языков')
    file = models.FileField(upload_to='users/static/users/resumes', null=True, blank=True)
    created_at = models.DateTimeField('Дата создания', default=timezone.now)

    def __str__(self):
        return f"Resume {self.id} - {self.job_seeker_profile.user.username}"

# Класс для профиля соискателей работы
class JobSeekerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='job_seeker_profile')
    resume = models.OneToOneField(Resume, on_delete=models.SET_NULL, null=True, blank=True)
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE, related_name='job_seekers', null=True, blank=True)
    created_at = models.DateTimeField('Дата создания', default=timezone.now)
    status = models.BooleanField(default=False)
    phone_number = models.CharField(
        max_length=15,
        blank=True,
        null=True,
        verbose_name='Номер телефона',
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', message="Введите корректный номер телефона")]
    )  # Новое поле для телефона
    date_of_birth = models.DateField(
        blank=True,
        null=True,
        verbose_name='Дата рождения'
    )  # Новое поле для даты рождения
    avatar = models.ImageField(
        upload_to='users/static/users/img',  # Папка для сохранения изображений
        default='users/static/users/img/defaultUserAvatar.svg',  # Значение по умолчанию
        blank=True,
        null=True,
        verbose_name='Аватар'
    )  # Новое поле для аватара

    def __str__(self):
        return f"Job Seeker {self.user.username}"

work/models.py
from django.db import models
from django.utils import timezone

# Класс категорий профессий
class JobCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название категории профессий')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')

    def __str__(self):
        return self.name

# Класс профессий
class Profession(models.Model):
    name = models.CharField(max_length=70, unique=True, verbose_name='Название профессии')
    category = models.ForeignKey(JobCategory, on_delete=models.CASCADE, related_name='professions', verbose_name='Категория')

    def __str__(self):
        return self.name

# Класс вакансий
class Vacancy(models.Model):  # Исправил опечатку с 'Vacansy'
    JOB_TYPES = [
        ('full_time', 'Полный рабочий день'),
        ('part_time', 'Неполный рабочий день'),
        ('contract', 'Контракт'),
        ('internship', 'Стажировка'),
    ]

    employer = models.ForeignKey('users.EmployerProfile', on_delete=models.CASCADE, verbose_name='Работодатель')
    title = models.CharField(max_length=255, verbose_name='Название вакансии')
    requirements = models.TextField(blank=True, null=True, verbose_name='Описание вакансии')
    responsibilities = models.TextField(blank=True, null=True, verbose_name='Обязанности')  # Исправил 'responsobilities'
    salary_min = models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')
    salary_max = models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')
    experience_required = models.IntegerField(blank=True, null=True, verbose_name='Требуемый опыт работы (в годах)')
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE, related_name='vacancies', verbose_name='Профессия')  # Связь с Profession
    category = models.ForeignKey(JobCategory, on_delete=models.RESTRICT, verbose_name='Категория профессии')
    location = models.CharField(max_length=255, blank=True, null=True, verbose_name='Место работы')
    is_active = models.BooleanField(default=True, verbose_name='Статус вакансии')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    job_type = models.CharField(max_length=20, choices=JOB_TYPES, verbose_name='Тип занятости')

    def __str__(self):
        return self.title

class Application(models.Model):
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('reviewed', 'Рассмотрено'),
        ('accepted', 'Принято'),
        ('rejected', 'Отклонено'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    def get_status_css_class(self):
        return {
            'pending': 'status pending',
            'reviewed': 'status reviewed',
            'accepted': 'status accepted',
            'rejected': 'status rejected',
        }.get(self.status, 'status')

    vacancy = models.ForeignKey(
        'work.Vacancy',
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Вакансия'
    )
    job_seeker = models.ForeignKey(
        'users.JobSeekerProfile',
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Соискатель'
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name='Дата подачи'
    )

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending', verbose_name='Статус отклика')

    def __str__(self):
        return f"Application: {self.job_seeker.user.username} to {self.vacancy.title}"

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date
from users.models import EmployerProfile, JobSeekerProfile, Resume
from work.models import JobCategory

User = get_user_model()



# Форма регистрации
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-input',
            'placeholder': ''
        })
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': ''
        })
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': ''
        })
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': ''
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    # Функции обработки ошибки, если такой емейл уже существует.
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Аккаунт с данным адресом электронной почты уже существует!')
        return email


# Форма для страницы редактирования профиля работодателя.
class EmployerProfileForm(forms.ModelForm):
    class Meta:
        model = EmployerProfile
        fields = ['company_name', 'company_description', 'company_address', 'company_logo']


from django import forms
from .models import JobSeekerProfile
import datetime

# Форма для редактирования профиля соискателя.
class JobSeekerProfileForm(forms.ModelForm):
    # Это вытаскивание полей из модельки юзера.
    username = forms.CharField(
        label="Имя пользователя",
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'})
    )
    first_name = forms.CharField(
        label="Имя",
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Введите свое имя'})
    )
    last_name = forms.CharField(
        label="Фамилия",
        max_length=150,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Введите свою фамилию'})
    )
    # Вытаскивание поля категории
    category = forms.ModelChoiceField(queryset=JobCategory.objects.all(), required=False, label="Категория")

    date_of_birth = forms.DateField(
        label="Дата рождения",
        widget=forms.DateInput(attrs={
            'type': 'date',
            'placeholder': 'Выберите дату рождения',
        }),
        required=False
    )

    avatar = forms.ImageField(
        label="Аватарка",
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control',
            'style': 'border: 1px solid #ccc; padding: 10px;',
        })
    )

    class Meta:
        model = JobSeekerProfile
        fields = ['username', 'first_name', 'last_name', 'category',
                  'status', 'profession','phone_number', 'date_of_birth', 'avatar']
        widgets = {
            'status': forms.RadioSelect(choices=[(True, 'Ищу работу'), (False, 'Не ищу работу')]),
            'experience': forms.TextInput(attrs={'placeholder': 'Введите опыт работы в годах'}),
            'profession': forms.Select(attrs={'placeholder': 'Выберите профессию'}),
        }

    # Функция инициализации полей юзера и добавление их в БД.
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(JobSeekerProfileForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['username'].initial = user.username
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name

            # Проходим по всем полям формы и устанавливаем начальные значения из экземпляра модели
        for field in self.fields:
            field_value = getattr(self.instance, field, None)
            if field_value is not None:
                # Преобразуем в строку, если это необходимо (например, для дат)
                if isinstance(field_value, datetime.date):
                    field_value = field_value.strftime('%Y-%m-%d')
                self.fields[field].initial = field_value

        profile = kwargs.pop('profile', None)  # Получаем профиль
        if profile:
            self.fields[
                'date_of_birth'].initial = profile.date_of_birth or ''  # устанавливаем пустое значение, если дата не указана
            self.fields['status'].initial = profile.status  # Обратите внимание на это

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if date_of_birth:  # Если дата рождения указана
            # Проверка на возраст 18 лет
            today = date.today()
            age = today.year - date_of_birth.year
            if today.month < date_of_birth.month or (today.month == date_of_birth.month and today.day < date_of_birth.day):
                age -= 1
            if age < 18:
                raise ValidationError("Возраст должен быть не менее 18 лет.")
        # Если дата рождения не указана, возвращаем None (для пустого значения)
        return date_of_birth

    def save(self, commit=True):
        profile = super(JobSeekerProfileForm, self).save(commit=False)
        user = profile.user

        # Сохраняем данные пользователя
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        # Обработка даты рождения
        date_of_birth = self.cleaned_data.get('date_of_birth', None)
        if date_of_birth is not None:
            print(f"Сохраняем дату рождения: {date_of_birth}")  # Отладка
            profile.date_of_birth = date_of_birth
        else:
            print("Дата рождения не передана.")  # Отладка
            # Если дата не была изменена, оставляем текущее значение
            profile.date_of_birth = self.instance.date_of_birth

        if commit:
            user.save()
            profile.save()

        return profile


import re
from django import forms
from django.core.exceptions import ValidationError
from .models import Resume

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['education', 'summary', 'skills', 'languages', 'experience']

    # Валидация языков
    def clean_languages(self):
        languages = self.cleaned_data.get('languages')
        if languages:
            # Проверяем формат: слова разделены запятыми, без лишних пробелов
            if not re.match(r'^[a-zA-Zа-яА-ЯёЁ]+(, ?[a-zA-Zа-яА-ЯёЁ]+)*$', languages):
                raise ValidationError(
                    "Языки должны быть перечислены через запятую (например: Английский, Русский, Немецкий)."
                )
            # Приводим к единому формату (удаляем лишние пробелы)
            languages = ", ".join(language.strip() for language in languages.split(","))
        return languages

users/templates/users/activation_complete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение почты</title>
    <link rel="stylesheet" href="{% static 'users/css/activation_complete.css' %}">
</head>
<body>
    <div class="container">
        <h1>Подтверждение почты!</h1>
        <p>
            Мы отправили активационное письмо на ваш email.
            Пожалуйста, проверьте почту и нажмите на ссылку, чтобы завершить активацию.
        </p>
        <a href="mailto:soslippyyy@gmail.com">
            <button>Связаться с поддержкой</button>
        </a>
        <div class="footer">
            Если письмо не пришло, проверьте папку "Спам" или повторите попытку через 10 минут.
        </div>
        <a href="/" class="back-home">Вернуться на главную</a>
    </div>
</body>
</html>

users/templates/users/active.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Активация аккаунта</title>
</head>
<body>
    <h2>Ваш аккаунт был успешно активирован!</h2>
    <p>Теперь вы можете войти в систему.</p>
    <a href="{% url 'login' %}">Войти</a>
</body>
</html>

users/templates/users/create_vacancy.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создание вакансии</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/create_vacancy.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header class="left-panel">
        <div class="logotype">
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav class="nav-menu">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Профиль</a>
            <a href="{% url 'applications' %}">Отклики</a>
            {% if user.employer_profile %}  <!-- Проверяем, является ли пользователь работодателем -->
            <a href="{% url 'employer_vacancies' %}">Мои вакансии</a>  <!-- Ссылка на страницу списка вакансий -->
        {% endif %}
            <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button class="leave">Выйти</button>
            </form>

        {% else %}

            <a href="{% url 'login' %}" >Войти</a>
            <button onclick="{% url 'register' %}" class="button">Зарегистрироваться </button>
        {% endif %}

    </nav>
    </header>

    <div class="container">
        <h1>Создание вакансии</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_title">Название вакансии
                    <span class="tooltip">?<span class="tooltip-text">Укажите название вакансии.</span></span>
                </label>
                {{ form.title }}
            </div>

            <div class="form-group">
                <label for="id_requirements">Описание вакансии
                    <span class="tooltip">?<span class="tooltip-text">Опишите требования и задачи.</span></span>
                </label>
                {{ form.requirements }}
            </div>

            <div class="form-group">
                <label for="id_responsibilities">Обязанности
                    <span class="tooltip">?<span class="tooltip-text">Перечислите основные обязанности.</span></span>
                </label>
                {{ form.responsibilities }}
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="id_salary_min">Мин. зарплата
                        <span class="tooltip">?<span class="tooltip-text">Минимальная зарплата.</span></span>
                    </label>
                    {{ form.salary_min }}
                </div>
                <div class="form-group">
                    <label for="id_salary_max">Макс. зарплата
                        <span class="tooltip">?<span class="tooltip-text">Максимальная зарплата.</span></span>
                    </label>
                    {{ form.salary_max }}
                </div>
            </div>

            <div class="form-group">
                <label for="id_category">Категория профессии
                    <span class="tooltip">?<span class="tooltip-text">Выберите категорию.</span></span>
                </label>
                {{ form.category }}
            </div>

            <div class="form-group">
                <label for="id_profession">Профессия
                    <span class="tooltip">?<span class="tooltip-text">Выберите профессию.</span></span>
                </label>
                {{ form.profession }}
            </div>

            <div class="form-group">
                <label for="id_experience_required">Требуемый опыт (лет)
                    <span class="tooltip">?<span class="tooltip-text">Требуемый опыт работы.</span></span>
                </label>
                {{ form.experience_required }}
                {% if form.experience_required.errors %}
                    <ul class="error-list">
                        {% for error in form.experience_required.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_job_type">Тип занятости
                    <span class="tooltip">?<span class="tooltip-text">Выберите тип занятости.</span></span>
                </label>
                {{ form.job_type }}
            </div>

            <div class="form-group">
                <label for="id_location">Место работы
                    <span class="tooltip">?<span class="tooltip-text">Укажите место работы.</span></span>
                </label>
                {{ form.location }}
            </div>

            {{ form.is_active }}

            <button type="submit">Создать вакансию</button>
        </form>
    </div>

    <!-- Скрипт для фильтрации профессий по категории -->
    <script>
        $('#id_category').change(function() {
            var categoryId = $(this).val();

            // Отправка AJAX-запроса для получения профессий по категории
            $.ajax({
                url: "{% url 'load_professions' %}",
                data: {
                    'category_id': categoryId
                },
                success: function(data) {
                    var professionSelect = $('#id_profession');
                    professionSelect.empty();  // Очистка существующих опций

                    // Добавление новой опции по умолчанию
                    professionSelect.append('<option value="">Выберите профессию</option>');

                    // Заполнение выпадающего списка новыми данными
                    $.each(data, function(key, value) {
                        professionSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                }
            });
        });
    </script>
</body>
</html>

users/templates/users/edit_resume.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактирование резюме</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/edit_resume.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>

    <header class="left-panel">
        <div class="logotype">
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav class="nav-menu">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Назад в профиль</a>
            <a href="{% url 'applications' %}">Отклики</a>
            {% if user.employer_profile %}  <!-- Проверяем, является ли пользователь работодателем -->
            <a href="{% url 'employer_vacancies' %}">Мои вакансии</a>  <!-- Ссылка на страницу списка вакансий -->
        {% endif %}

        {% endif %}

    </nav>
    </header>

    <div class="container">
        <h1>Редактирование резюме</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_education">Образование
                    <span class="tooltip">?
                        <span class="tooltip-text">Выберите уровень вашего образования (например, бакалавр, магистр).</span>
                    </span>
                </label>
                {{ form.education }}
            </div>

            <div class="form-group">
                <label for="id_summary">Краткое описание
                    <span class="tooltip">?
                        <span class="tooltip-text">Опишите себя, свои сильные стороны и цели в трёх-четырёх предложениях.</span>
                    </span>
                </label>
                {{ form.summary }}
            </div>

            <div class="form-group">
                <label for="id_skills">Навыки
                    <span class="tooltip">?
                        <span class="tooltip-text">Перечислите и опишите навыки, которыми владеете в вашей профессии.</span>
                    </span>
                </label>
                {{ form.skills }}
            </div>

            <div class="form-group">
                <label for="id_languages">Языки
                    <span class="tooltip">?
                        <span class="tooltip-text">Укажите через запятую языки, которыми владеете (например, Русский, Английский).</span>
                    </span>
                </label>
                {{ form.languages }}
                {% if form.languages.errors %}
                    <div class="error-list">
                        {% for error in form.languages.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_experience">Опыт работы (в годах)</label>
                {{ form.experience }}
                {% if form.experience.errors %}
                    <div class="error-list">
                        {% for error in form.experience.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <button type="submit">Сохранить изменения</button>
        </form>
    </div>

</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/register.css' %}">
</head>
<body>
        <header class="left-panel">
        <div class="logotype" >
            <a href="{% url 'home' %}"><img src="{% static 'users/img/Logo.svg' %}" alt="HiredUp Logo"></a>
        </div>

        <nav class="nav-menu">
            <a href="{% url 'home' %}">Главная</a>
            <a href="{% url 'login' %}">Войти</a>
            <a href="#profile">Вакансии дня</a>
            <a href="#register">Помощь</a>
            <a href="#login">Еще что-то</a>
        </nav>
    </header>



<div class="main-content">
    <h1>Регистрация</h1>
    <h2>Зарегистрируйтесь чтобы работодатель или работник мог связаться с вами</h2>
    <div class="form-container">
        <form method="POST" class="registration-form form">
            {% csrf_token %}
            <!-- Поля формы -->
            <div class="form-group">
                {{ form.username }}
                <label for="id_username">Имя пользователя</label>

                <div class="error">{{ form.username.errors }}</div>
            </div>
            <div class="form-group">
                {{ form.email }}
                <label for="id_email">Email</label>
                <div class="error">{{ form.email.errors }}</div>
            </div>

            <div class="form-group">
                {{ form.password1 }}
                <label for="id_password1">Пароль</label>
                <div class="error">{{ form.password1.errors }}</div>
            </div>

            <div class="form-group">
                {{ form.password2 }}
                <label for="id_password2">Подтверждение пароля</label>
                <div class="error">{{ form.password2.errors }}</div>
            </div>
    </div>
            <!-- Кнопки для выбора типа пользователя -->


    <div class="user-type-buttons">
                <button type="submit" name="user_type" value="job_seeker">
                    <span class ="text">Я ищу работу</span>
                </button>
                <button type="submit" name="user_type" value="employer">
                    <span class ="text">Я ищу сотрудников</span>
                </button>

    </div>

        <p>Уже есть аккаунт? <a href="{% url 'login' %}">Войдите</a></p>
    </form>
<footer>
        <p>&copy; 2024 HiredUp</p>
    </footer>
</div>

</body>
</html>